import { prisma } from '../config/prisma.js';
import QRCode from 'qrcode';
import crypto from 'crypto';
import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
export async function dashboard(req, res) { const [employees, departments, today] = await Promise.all([prisma.employee.count(), prisma.department.count(), prisma.attendance.count({ where: { date: new Date(new Date().toDateString()) } })]); res.json({ employees, departments, todayAttendances: today }); }
export const listEmployees = async (req, res) => res.json(await prisma.employee.findMany({ include: { user: true, department: true, position: true, schedule: true } }));
export async function updateEmployee(req, res) { res.json(await prisma.employee.update({ where: { id: Number(req.params.id) }, data: req.body })); }
export const makeCrud = (model) => ({ list: async (_req,res)=>res.json(await prisma[model].findMany()), create: async (req,res)=>res.status(201).json(await prisma[model].create({ data:req.body })), update: async (req,res)=>res.json(await prisma[model].update({ where:{ id:Number(req.params.id) }, data:req.body })), remove: async (req,res)=>res.json(await prisma[model].delete({ where:{ id:Number(req.params.id) } })) });
export async function generateQr(req, res) { const token = crypto.randomBytes(32).toString('hex'); const expiresAt = new Date(Date.now() + 5 * 60_000); await prisma.qrToken.create({ data: { token, expiresAt, createdById: req.user.id } }); res.json({ token, expiresAt, qrDataUrl: await QRCode.toDataURL(token) }); }
export async function monitor(req, res) { res.json(await prisma.attendance.findMany({ include: { employee: true }, orderBy: { createdAt: 'desc' }, take: 100 })); }
export async function reports(req, res) { const rows = await prisma.attendance.findMany({ include: { employee: true }, orderBy: { date: 'desc' } }); if (req.query.format === 'pdf') { const doc = new PDFDocument(); res.setHeader('Content-Type','application/pdf'); doc.pipe(res); doc.text('Attendance Report'); rows.forEach(r=>doc.text(`${r.date.toISOString().slice(0,10)} ${r.employee.firstName} ${r.employee.lastName} ${r.status}`)); return doc.end(); } const wb = new ExcelJS.Workbook(); const ws = wb.addWorksheet('Attendance'); ws.columns = ['Date','Employee','Check In','Check Out','Status'].map((header)=>({ header, key: header })); rows.forEach(r=>ws.addRow({ Date: r.date, Employee: `${r.employee.firstName} ${r.employee.lastName}`, 'Check In': r.checkInAt, 'Check Out': r.checkOutAt, Status: r.status })); res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); await wb.xlsx.write(res); res.end(); }

export function modules(_req, res) { res.json({ modules: [{ name: 'Employee Management', description: 'Manage employee profiles and assignments.', path: '/api/admin/employees' }, { name: 'Department Catalog', description: 'Create and maintain organization departments.', path: '/api/admin/departments' }, { name: 'Position Catalog', description: 'Create and maintain employee positions.', path: '/api/admin/positions' }, { name: 'Work Schedules', description: 'Configure start times, end times, and grace periods.', path: '/api/admin/schedules' }, { name: 'QR Generator', description: 'Generate short-lived QR tokens for attendance scans.', path: '/api/admin/qr' }, { name: 'Attendance Monitoring', description: 'Monitor recent check-in and check-out activity.', path: '/api/admin/monitor' }, { name: 'Reports', description: 'Export attendance reports in Excel or PDF format.', path: '/api/admin/reports' }] }); }
